import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from difflib import SequenceMatcher
from typing import Any, Optional, Union

from redlines.document import Document
from .style_parser import StyleParser

# This tokenizer splits text into words and whitespace sequences.
tokenizer = re.compile(r'(\s+|\S+)')

space_pattern = re.compile(r'(\s+)')


def tokenize_text(text: str) -> list[str]:
    """
    Splits text into words, punctuation, and whitespace, preserving all three.
    """
    # \w+ matches one or more word characters (letters, numbers, underscore)
    # [^\w\s] matches a single character that is not a word character or whitespace (i.e., punctuation)
    # \s+ matches one or more whitespace characters
    return re.findall(r"\w+|[^\w\s]|\s+", text)


def concatenate_paragraphs_and_add_chr_182(text: str) -> str:
    r"""Replaces paragraph breaks (2+ newlines) with ' ¶ ' and other newlines with a space."""
    # Replace 2+ newlines (paragraph breaks) with a paragraph marker
    # The marker is padded with spaces to ensure it's a separate token
    processed_text = re.sub(r'\n{2,}', ' ¶ ', text)
    # Replace remaining single newlines with a space
    processed_text = processed_text.replace('\n', ' ')
    return processed_text

@dataclass
class Chunk:
    """A chunk of text that is being compared. In some cases, it may be the whole document."""
    text: list[str]
    chunk_location: Optional[str]
    styles: Optional[list[Optional[dict[str, Any]]]] = None
    metadata: Optional[dict[str, Any]] = None

    def slice_text(self, start: int, end: int) -> str:
        if start >= end:
            return ''
        return ''.join(self.text[start:end])

    def slice_styles(self, start: int, end: int) -> Optional[list[Optional[dict[str, Any]]]]:
        if self.styles is None or start >= end:
            return None
        return self.styles[start:end]

@dataclass
class Redline:
    """A redline that is generated by the redlines library."""
    source_chunk: Chunk
    test_chunk: Chunk
    opcodes: tuple[str, int, int, int, int]
    metadata: Optional[dict[str, Any]] = None

    def to_dict(self, *, include_tokens: bool = False) -> dict[str, Any]:
        tag, i1, i2, j1, j2 = self.opcodes
        source_segment = {'start': i1, 'end': i2, 'text': self.source_chunk.slice_text(i1, i2)}
        test_segment = {'start': j1, 'end': j2, 'text': self.test_chunk.slice_text(j1, j2)}
        if include_tokens:
            source_segment['tokens'] = self.source_chunk.text[i1:i2]
            test_segment['tokens'] = self.test_chunk.text[j1:j2]
        if self.source_chunk.metadata:
            source_segment['metadata'] = self.source_chunk.metadata
        if self.test_chunk.metadata:
            test_segment['metadata'] = self.test_chunk.metadata
        return {'type': tag, 'source': source_segment, 'test': test_segment, 'metadata': self.metadata or {}}

class RedlinesProcessor(ABC):
    @abstractmethod
    def process(self, source: Union[Document, str], test: Union[Document, str]) -> list[Redline]:
        pass

class WholeDocumentProcessor(RedlinesProcessor):
    """
    A redlines processor that compares two documents. It is style-aware and
    compares word by word.
    """
    def process(self, source: Union[Document, str], test: Union[Document, str]) -> list[Redline]:
        source_text = (source.text if isinstance(source, Document) else source).strip()
        test_text = (test.text if isinstance(test, Document) else test).strip()

        source_tokens, source_styles = self._get_tokens_and_styles(source_text)
        test_tokens, test_styles = self._get_tokens_and_styles(test_text)

        seq_source_normalized = [token.strip() for token in source_tokens]
        seq_test_normalized = [token.strip() for token in test_tokens]

        matcher = SequenceMatcher(None, seq_source_normalized, seq_test_normalized, autojunk=False)

        return [
            Redline(
                source_chunk=Chunk(text=source_tokens, chunk_location=None, styles=source_styles),
                test_chunk=Chunk(text=test_tokens, chunk_location=None, styles=test_styles),
                opcodes=opcode,
            )
            for opcode in matcher.get_opcodes()
        ]

    def _get_tokens_and_styles(self, text: str) -> tuple[list[str], Optional[list[Optional[dict[str, Any]]]]]:
        """
        Tokenizes text and extracts styles. It handles both plain text and HTML-like content.
        """
        text_with_para_markers = concatenate_paragraphs_and_add_chr_182(text)

        if '<' in text_with_para_markers and '>' in text_with_para_markers:
            parser = StyleParser()
            segments = parser.parse(text_with_para_markers)
            tokens, styles = [], []
            for seg_text, style in segments:
                seg_tokens = tokenize_text(seg_text)
                tokens.extend(seg_tokens)
                styles.extend([style] * len(seg_tokens))
            return tokens, styles
        else:
            tokens = tokenize_text(text_with_para_markers)
            return tokens, None